# Generated by Django 3.2.13 on 2022-04-14 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0023_globalpagepermission_can_set_as_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='in_navigation',
            field=models.BooleanField(db_index=True, default=False, verbose_name='in navigation'),
        ),
    ]
