name: django CMS frontend.yml

on: [push, pull_request]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true


jobs:
  frontend:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: [6.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm install -g gulp@3.9.1
    - run: |
          gulp tests:unit
          gulp lint
